export const people = [
  {
    id: 1,
    mail: "usuario1@gmail.com",
    nombre: "Usuario1",
    esPremium: true,
    foto: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQnbQ2Q4xm23t64HCDMiGTJ_WZuHD5-EVBe-A&usqp=CAU",
    puntosEjercicio: 50,
    puntosAgua: 30,
    puntosComida: 30,
  },
  {
    id: 2,
    mail: "usuario2@gmail.com",
    nombre: "Usuario2",
    esPremium: false,
    foto: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQWt27nwLDyc1fU2NMT6fmZ6rthrtQf7b3EIheNs20A4nN33o1Da8NjMvgAFRzMRCl9I80&usqp=CAU",
    puntosEjercicio: 100,
    puntosAgua: 30,
    puntosComida: 30,
  },
  {
    id: 3,
    mail: "usuario3@gmail.com",
    nombre: "Usuario3",
    esPremium: false,
    foto: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQfkRUFbRCu8_U1DONl-p20GAKs9IgOrmqraQGftl7OviG8kyHrAoBkIy2FESZfobm-llU&usqp=CAU",
    puntosEjercicio: 90,
    puntosAgua: 50,
    puntosComida: 10,
  },
  {
    id: 4,
    mail: "usuario4@gmail.com",
    nombre: "Usuario4",
    esPremium: true,
    foto: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSlfXvFOv9vqsiig8wUX7UKD7Do6UmEdUvQiDTsEOVL1hrWgeurTJWP0L3YsrELGS6sCew&usqp=CAU",
    puntosEjercicio: 20,
    puntosAgua: 50,
    puntosComida: 10,
  },
  {
    id: 5,
    mail: "usuario5@gmail.com",
    nombre: "Usuario5",
    esPremium: false,
    foto: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQQwwmvajdhtL4FE4KAHHeZxbpRcertgtEPFyCWh9p_7zxd-WdG2FyUEj4NzpiVz8_yneU&usqp=CAU",
    puntosEjercicio: 10,
    puntosAgua: 20,
    puntosComida: 20,
  },
];
